#!/bin/sh
git --work-tree=/usr/local/hexo/source_posts --git-dir=/usr/local/blog/blog.git checkout -f;
cd /usr/local/hexo;
hexo clean;
hexo g;
# rm -rf /data/wzh-blog/www/*; cp -r /data/wzh-blog/hexo/public/* /data/wzh-blog/www;
